const AppImages = {
    Logo: require('../assets/images/logo.png'),
    Email: require('../assets/images/email.png'),
    Lock: require('../assets/images/lock.png'),
    User: require('../assets/images/user.png'),
    Apple: require('../assets/images/apple.png'),
    Facebook: require('../assets/images/facebook.png'),
    Google: require('../assets/images/google.png'),
    Checkbox: require('../assets/images/checkbox.png'),
    Back: require('../assets/images/back.png'),
    RightIcon: require('../assets/images/rightIcon.png'),
    Profile: require('../assets/images/profile.png'),
    Shield: require('../assets/images/shield.png'),
    ProfileUser: require('../assets/images/profileUser.png'),
    People: require('../assets/images/people.png'),
    Camera: require('../assets/images/camera.png'),
    BG: require('../assets/images/bg.png'),
    Shadow: require('../assets/images/shadow.png'),
    Tab1: require('../assets/images/tab1.png'),
    Tab2: require('../assets/images/tab2.png'),
    Tab3: require('../assets/images/tab3.png'),
    Tab4: require('../assets/images/tab4.png'),
    Tab5: require('../assets/images/tab5.png'),
}

export default AppImages